### ISSUE TITLE
bug: js-waku peer exchange interop bug

### ISSUE THREAD

**Issue by danisharora099** [waku-org/nwaku#1428]
### Problem
As a partial followup to https://github.com/waku-org/nwaku/issues/1408, the changes in js-waku to handle an inbound connection was handled upon which the connection was established and response was received by js-waku.
Upon further confirmations, it is seen that the the received response when decoded results in:
1. empty array
2. different `query` than sent

### Impact
Blocks Peer Exchange in js-waku

### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Go to js-waku
2. Checkout to `danisharora/peer-exchnage-refactor-protocol`
3. `cd packages/tests` && `yarn test`

### Expected behavior
The ENRs of the two nwaku nodes connected should be returned as part of the response in an array.

### Screenshots/logs
1. Logs for nwaku: 
(Nwaku node 1 is enabled with Peer Exchange while Node 2 and Node 3 are connecting to Node 1 using discv5 discovery.
[nwaku_node3.log](https://github.com/waku-org/nwaku/files/10104768/nwaku_node3.log)
[nwaku_node1.log](https://github.com/waku-org/nwaku/files/10104765/nwaku_node1.log) -> running Peer Exchange
[nwaku_node2.log](https://github.com/waku-org/nwaku/files/10104767/nwaku_node2.log) 

2. Inconsistency in `request` as seen before sending, and after the response:
```
encoded req { query: { numPeers: 1n }, response: undefined }
decoded-res { query: { numPeers: 0n }, response: { peerInfos: [] } }
```
It can be seen that the `numPeers` requested were `1n`, but the `request` in the received response has `numPeers` as `0n`

### nwaku version/commit hash
nwaku is running on the latest master 

### Additional context
- Since the `numPeers` are inconsistent with the ones requested for, and are always to set 0n, is why an emptp array of peer info is sent?
- I can still spot `ENR cache is empty` in the nwaku node's log running PX, while it can also be seen that 2 peers are connected to it.

**Comment by danisharora099** [comment]
> > Inconsistency in request as seen before sending, and after the response:
> 
> Do you send both requests to Node 1 within a short time window? In this case, you (currently) can't map them to the respective query because there is no request ID. This will be addressed in the peer-exchange overhaul, as we most likely move to a Waku req/resp style. (Note: This is not expected behaviour, because you could just ask for more peers in a single query.)

I start my node 1 with PX enabled, have the other two nwaku nodes connect to it immediately after with discv5Discovery.
I then wait 40 seconds before creating a js-waku node and sending the peer exchange query.
I have tried sending a request to fetch `1n` peers & `2n` peers, both of which result in an empty response array.

> 
> > I can still spot ENR cache is empty in the nwaku node's log running PX, while it can also be seen that 2 peers are connected to it.
> 
> Do all peers have enough time before you send the request? There is a separate discv5 loop for peer exchange which runs less frequent than the main discv5 loop.

Yes. I wait for 40 seconds before requesting for the ENRs.

@kaiserd

**Comment by danisharora099** [comment]
> In the logs you provided, node1 did not discover any nodes via discv5. So it seems, the problem is not related to peer-exchange (or at least, there is another problem shadowing the peer-exchange problem).

Not sure what it implies but tt does say `peers=2`, which I assumed are the 2 nodes it discovered.

**Comment by fryorcraken** [comment]
@kaiserd we are using `--discv5-nootstrap-node` when starting the nwaku node.

If:
- Starts node 1
- Starts node 2 with `-discv5-nootstrap-node=<node 1>`

1. Should a peer exchange request on node 1 return node 2?
2. Should a peer exchange request on node 2 return node1?
3. If (1) or (2) is yes, then how long should it take for the peer to be included in the peer exchange request?

**Comment by fryorcraken** [comment]
@kaiserd Also, are the latest fixes deployed on wakuv2.test fleet? If so, @danisharora099 you can trying to target the test fleet for testing to confirm it works first, and then try to sort out the CI.

@richard-ramos if you do a peer exchange request with go-waku to the wakuv2. test fleet, does it return peers?

**Comment by richard-ramos** [comment]
I get a "protocol not supported" error. Is peer exchange enabled in the test fleet?

**Comment by danisharora099** [comment]
> @danisharora099
> 
> > I added a delay of 10 secs, as discussed, after each nwaku node runs to allow for discv5 to occur -- no luck on my end -- still receiving the empty ENR cache in the log.
> 
> #1051 shows a testcase that works on my machine.
> 
>     * Node1 finds both node2 and node3 via discv5
> 
>     * Node1 finds both node2 and node3 in the peer exchange discv5 loop
> 
> 
> `Discovered px peers via discv5 .... count=2 ...`
> 
> (There are strange characters in the js-waku logs for nwaku, so I copied and edited the relevant info.)

I think you meant https://github.com/waku-org/js-waku/pull/1051 😅 

Also, can you explain what you mean by "works on my machine"?
Do you receive the expected peer info on the JS logs?
I still can't seem to reproduce the expected behavior on your branch

**Comment by danisharora099** [comment]
This has now been resolved. Thanks all :)
